name: "Swift install"
description: "Install Swift"
branding:
    icon: award
    color: purple

inputs:
    swift-release:
        description: "the identifier of a Swift release toolchain, such as '6.3-RELEASE', \
            if using automatic parameter configuration"
        required: false
        type: string

    swift-prefix:
        description: "The URL prefix to download the Swift toolchain from, \
            if installing Swift. The string should be a valid directory under \
            download.swift.org, such as 'swift-6.2.4-release/ubuntu2404/swift-6.2.4-RELEASE'"
        required: false
        type: string

    swift-id:
        description: "The Swift toolchain version to install. This should be a full toolchain \
          identifier, including the platform, like 'swift-6.2.4-RELEASE-ubuntu24.04'"
        required: false
        type: string

runs:
    using: composite
    steps:
        -   name: Select Swift toolchain
            id: parameters
            shell: bash
            env:
                SWIFT_VERSION: ${{ inputs.swift-release }}
                SWIFT_PREFIX: ${{ inputs.swift-prefix }}
                SWIFT_ID: ${{ inputs.swift-id }}
            run: |
                if [[ -n "$SWIFT_VERSION" ]]; then
                    if [[ -n "$SWIFT_PREFIX" || -n "$SWIFT_ID" ]]; then
                        echo "::error:: Cannot combine 'swift-release' with 'swift-prefix' or 'swift-id'"
                        exit 1
                    fi

                    if [[ "$RUNNER_OS" == "Linux" ]]; then
                        if ! command -v lsb_release &> /dev/null; then
                            echo "::error:: Auto-configuration requires 'lsb_release', which was not found!"
                            exit 1
                        fi

                        UBUNTU_VERSION="ubuntu$(lsb_release -rs)"
                        SWIFT_PLATFORM="${UBUNTU_VERSION}-$(uname -m)"
                        SWIFT_PLATFORM="${SWIFT_PLATFORM%-x86_64}"

                        SWIFT_PREFIX="swift-${SWIFT_VERSION,,}/${SWIFT_PLATFORM//[.]/}/swift-${SWIFT_VERSION}"
                        SWIFT_ID="swift-${SWIFT_VERSION}-${SWIFT_PLATFORM}"

                    elif [[ "$RUNNER_OS" == "macOS" ]]; then
                        # bash 4 not available on macOS
                        SWIFT_BRANCH="swift-$(echo "$SWIFT_VERSION" | tr '[:upper:]' '[:lower:]')"
                        SWIFT_PREFIX="${SWIFT_BRANCH}/xcode/swift-${SWIFT_VERSION}"
                        SWIFT_ID="swift-${SWIFT_VERSION}"
                    else
                        echo "::error:: Auto-configuration not supported for $RUNNER_OS"
                        exit 1
                    fi
                elif [[ -z "$SWIFT_PREFIX" || -z "$SWIFT_ID" ]]; then
                    echo "::error:: You must provide either 'swift-release' or both 'swift-prefix' and 'swift-id'"
                    exit 1
                fi

                echo "swift-prefix=$SWIFT_PREFIX" >> $GITHUB_OUTPUT
                echo "swift-id=$SWIFT_ID" >> $GITHUB_OUTPUT

        -   name: Create installation directory
            shell: bash
            run: |
                mkdir ~/swift

        ### Linux-specific steps

        -   name: Cache Swift toolchain (Linux)
            id:   cache_swift_linux
            if: runner.os == 'Linux'
            uses: actions/cache@v5
            with:
                path: "~/swift/swift.tar.gz"
                key: "swift:${{ steps.parameters.outputs.swift-id }}.tar.gz"

        -   name: Download Swift (Linux)
            shell: bash
            if: runner.os == 'Linux' && steps.cache_swift_linux.outputs.cache-hit != 'true'
            env:
                SWIFT_PREFIX: ${{ steps.parameters.outputs.swift-prefix }}
                SWIFT_ID: ${{ steps.parameters.outputs.swift-id }}
            run: |
                curl https://download.swift.org/$SWIFT_PREFIX/$SWIFT_ID.tar.gz \
                    --output ~/swift/swift.tar.gz

        -   name: Install Swift (Linux)
            shell: bash
            if: runner.os == 'Linux'
            env:
                SWIFT_ID: ${{ steps.parameters.outputs.swift-id }}
            run: |
                mkdir ~/swift/$SWIFT_ID
                tar -xzf ~/swift/swift.tar.gz -C ~/swift/$SWIFT_ID --strip 1
                echo "SWIFT_INSTALLATION=$HOME/swift/$SWIFT_ID/usr" >> $GITHUB_ENV
                echo "$HOME/swift/$SWIFT_ID/usr/bin" >> $GITHUB_PATH

        ### macOS-specific steps
        ### Please note, on macOS, the `swift-id` does not include the `-osx` suffix!

        -   name: Cache Swift toolchain (macOS)
            id:   cache_swift_macos
            if: runner.os == 'macOS'
            uses: actions/cache@v5
            with:
                path: "~/swift/swift.pkg"
                key: "swift:${{ steps.parameters.outputs.swift-id }}.pkg"

        -   name: Download Swift (macOS)
            shell: bash
            if: runner.os == 'macOS' && steps.cache_swift_macos.outputs.cache-hit != 'true'
            env:
                SWIFT_PREFIX: ${{ steps.parameters.outputs.swift-prefix }}
                SWIFT_ID: ${{ steps.parameters.outputs.swift-id }}
            run: |
                curl https://download.swift.org/$SWIFT_PREFIX/$SWIFT_ID-osx.pkg \
                    --output ~/swift/swift.pkg

        -   name: Install Swift (macOS)
            shell: bash
            if: runner.os == 'macOS'
            env:
                SWIFT_ID: ${{ steps.parameters.outputs.swift-id }}
            run: |
                sudo installer -pkg ~/swift/swift.pkg -target /
                echo "SWIFT_INSTALLATION=/Library/Developer/Toolchains/$SWIFT_ID.xctoolchain/usr" >> $GITHUB_ENV
                echo "TOOLCHAINS=$(plutil -extract CFBundleIdentifier raw \
                    /Library/Developer/Toolchains/$SWIFT_ID.xctoolchain/Info.plist)" >> $GITHUB_ENV

        ### End platform-specific steps

        -   name: Check Swift
            shell: bash
            run: |
                $SWIFT_INSTALLATION/bin/swift --version
                cat $GITHUB_PATH
                swift --version
